models/Trainee.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;
use app\models\Training;
use yii\db\Query;

/**
 * This is the model class for table "trainee".
 *
 * @property integer $id
 * @property string $surname
 * @property string $firstname
 * @property string $middlename
 * @property string $phone
 * @property string $email
 * @property integer $gender
 * @property integer $state_id
 * @property integer $lga_id
 * @property integer $ward_id
 * @property integer $facility_id
 * @property integer $serviceyears
 * @property string $position
 * @property string $photo
 * @property string $create_time
 * @property integer $create_user
 * @property string $update_time
 * @property integer $update_user
 * @property number $latitude
 * @property number $longitude
 * @property string $comment
 * @property string $dateofbirth
 * @property Healthfacility $facility
 * @property Lga $lga
 * @property State $state
 */
class Trainee extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trainee';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gender', 'state_id', 'lga_id', 'facility_id','ward_id', 'serviceyears'], 'integer'],
            [['surname', 'firstname', 'middlename', 'phone', 'email', 'position'], 'string', 'max' => 255],
            [['facility_id'], 'exist', 'skipOnError' => true, 'targetClass' => Healthfacility::className(), 'targetAttribute' => ['facility_id' => 'id']],
            [['lga_id'], 'exist', 'skipOnError' => true, 'targetClass' => Lga::className(), 'targetAttribute' => ['lga_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => State::className(), 'targetAttribute' => ['state_id' => 'id']],
            [['surname', 'firstname', 'phone', 'email', 'position',
                'gender', 'state_id', 'lga_id', 'facility_id', 'serviceyears','dateofbirth'], 'required'],
            ['email', 'email'],
            [['latitude', 'longitude'], 'double'],
            //['comment','safe'],
            ['dateofbirth','date','format'=>'php:Y-m-d'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'surname' => 'Surname',
            'firstname' => 'First name',
            'middlename' => 'Middle name',
            'phone' => 'Phone',
            'email' => 'Email',
            'gender' => 'Gender',
            'state_id' => 'State of current deployment',
            'lga_id' => 'Local Government Area',
            'ward_id' => 'Ward',
            'facility_id' => 'Health Facility',
            'serviceyears' => 'Years left in service',
            'position' => 'Position',
            'photo' => 'Photo',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'comment' => 'Comments',
            'dateofbirth' => 'Date of birth',
            'create_time' => 'Create Time',
            'create_user' => 'Create User',
            'update_time' => 'Update Time',
            'update_user' => 'Update User',
        ];
    }
    
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => 'update_time',
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'create_user',
                'updatedByAttribute' => 'update_user',
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFacility()
    {
        return $this->hasOne(Healthfacility::className(), ['id' => 'facility_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLga()
    {
        return $this->hasOne(Lga::className(), ['id' => 'lga_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function geWard()
    {
        return $this->hasOne(Ward::className(), ['id' => 'ward_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(State::className(), ['id' => 'state_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHealthfacility()
    {
        return $this->hasOne(Healthfacility::className(), ['id' => 'facility_id']);
    }
    
    public function getTrainings()
    {
        return $this->hasMany(Training::className(), ['id' => 'training_id'])
            ->viaTable('trainee_training', ['trainee_id' => 'id']);
    }

    public static function getFullName($id)
    {
        $trainee = static::findOne($id);
        return ucfirst($trainee->surname." ".$trainee->firstname);
    }

    public static function getTrainingsByFacility($id)
    {
        $result = (new Query())
            ->select('training.id')->distinct()
            ->addSelect(['training.title', 'training.organizer', 'training.startdate', 'training.enddate', 'training.venue' ])
            ->from('training')
            ->join('INNER JOIN', 'trainee_training', 'training.id = trainee_training.training_id')
            ->join('INNER JOIN', 'trainee', 'trainee.id = trainee_training.trainee_id')
            ->join('INNER JOIN', 'healthfacility', 'healthfacility.id = trainee.facility_id')
            ->where('healthfacility.id = :facility_id', [':facility_id' => $id])
            ->orderBy('training.startdate')
            ->all();

        return $result;
    }

    public static function getTrainingCountByFacility($facility_id, $training_id)
    {
        $result = (new Query())
            ->select('training.id')
            ->from('training')
            ->join('INNER JOIN', 'trainee_training', 'training.id = trainee_training.training_id')
            ->join('INNER JOIN', 'trainee', 'trainee.id = trainee_training.trainee_id')
            ->join('INNER JOIN', 'healthfacility', 'healthfacility.id = trainee.facility_id')
            ->where('healthfacility.id = :facility_id', [':facility_id' => $facility_id])
            ->andWhere('training.id = :training', [':training' => $training_id])
            ->count();

        return $result;
    }

    public static function getTraineesByFacility($facility_id, $training_id)
    {
        $result = (new Query())
            ->select(['trainee.surname', 'trainee.firstname'])
            ->from('trainee')
            ->join('INNER JOIN', 'trainee_training', 'trainee.id = trainee_training.trainee_id')
            ->join('INNER JOIN', 'training', 'training.id = trainee_training.training_id')
            ->join('INNER JOIN', 'healthfacility', 'healthfacility.id = trainee.facility_id')
            ->where('healthfacility.id = :facility_id', [':facility_id' => $facility_id])
            ->andWhere('training.id = :training', [':training' => $training_id])
            ->orderBy('trainee.surname')
            ->all();

        return $result;
    }
}

controllers/TraineeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Trainee;
use app\models\TraineeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Training;
use app\models\PhotoUploadForm;
use yii\web\UploadedFile;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

/**
 * TraineeController implements the CRUD actions for Trainee model.
 */
class TraineeController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Trainee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TraineeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $trained = Trainee::find()->count();
        $query = new \yii\db\Query();
        $rows = $query->select('lga_id')->from('trainee')->distinct();
        $lgacount = count($rows->all());
        $ward_count = Trainee::find()->select('ward_id')->distinct()->count();

        $states = Trainee::find()->select('state_id')->distinct()->all();
        $s_distribution = [];
        $state_names = [];
        foreach($states as $s){
            $arr = [];
            $state = \app\models\State::getStateName($s->state_id);

            //required for chart coordinates
            $arr['name'] = $state;
            $arr['y'] = intval(Trainee::find()->where(['state_id' => $s->state_id])->count());

            //required for displaying markers on map
            $state_names[] = $state.', Nigeria';//this is for the map

            array_push($s_distribution, $arr);
        }
        $state_distribution = json_encode($s_distribution);
        $state_names = json_encode($state_names); //encode state names

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'trained' => $trained,
            'lgacount' => $lgacount,
            'ward_count' => $ward_count,
            'state_distribution' => $state_distribution,
            'state_names' => $state_names
        ]);
    }

    /**
     * Displays a single Trainee model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'training'=> \app\models\TraineeTraining::find()->where(['trainee_id'=>$id])->all()
        ]);
    }

    /**
     * Creates a new Trainee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed

    public function actionCreate()
    {
        $model = new Trainee();
        $training = new \app\models\TraineeTraining();
        $upload = new PhotoUploadForm();
        $upload->scenario = PhotoUploadForm::SCENARIO_CREATE;

        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post()) && $model->validate() && $training->load(Yii::$app->request->post()) && $training->validate()) {
            $upload->photo = UploadedFile::getInstance($upload, 'photo');
            $upload->upload();

            $model->photo = $upload->dbName;
            $model->save();
            foreach ($training->training_id as $t){
                $tt = new \app\models\TraineeTraining();
                $tt->trainee_id = $model->id;
                $tt->training_id = $t;
                $tt->save(false);
            }
            Yii::$app->session->setFlash('success_message',"The record has been created successfully");
            return $this->redirect(['view', 'id' => $model->id]);


    } else {
        return $this->render('create', [
            'model' => $model,
            'training' => $training,
            'upload' => $upload
        ]);
    }
    */

    /**
     * Creates a new Trainee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Trainee();
        $training = new \app\models\TraineeTraining();

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $training->load(Yii::$app->request->post()) && $training->validate()) {

            $model->save();
            foreach ($training->training_id as $t){
                $tt = new \app\models\TraineeTraining();
                $tt->trainee_id = $model->id;
                $tt->training_id = $t;
                $tt->save(false);
            }
            Yii::$app->session->setFlash('success_message',"The record has been created successfully");
            return $this->redirect(['view', 'id' => $model->id]);


    } else {
        return $this->render('create', [
            'model' => $model,
            'training' => $training,
        ]);
    }



    }

    /**
     * Updates an existing Trainee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     *
    public function actionUpdate($id)
    {
        $training = [];
        $upload = new PhotoUploadForm();
        $upload->scenario = PhotoUploadForm::SCENARIO_UPDATE;
        $model = $this->findModel($id);
        $trainings = \app\models\TraineeTraining::find()->where(['trainee_id'=>$id])->indexBy('id')->all();
        foreach($trainings as $t){
            $training[$t->training_id] = ['SELECTED'=>'SELECTED'];
        }
        $train = new \app\models\TraineeTraining;

        if (Yii::$app->request->isPost) {
            $upload->photo = UploadedFile::getInstance($upload, 'photo');
            if($upload->photo != NULL && $upload->upload()){
                if ($model->load(Yii::$app->request->post()) && $model->validate() && $train->load(Yii::$app->request->post()) && $train->validate()) {
                    $model->photo = $upload->dbName;
                    $model->save();

                    //delete traineetraining models and save again
                    \app\models\TraineeTraining::deleteAll(['trainee_id'=>$id]);
                    foreach ($train->training_id as $t){
                        $tt = new \app\models\TraineeTraining();
                        $tt->trainee_id = $model->id;
                        $tt->training_id = $t;
                        $tt->save(false);
                    }
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }elseif($upload->photo == NULL){
                if ($model->load(Yii::$app->request->post()) && $model->validate() && $train->load(Yii::$app->request->post()) && $train->validate()) {

                    $model->save();

                    //delete traineetraining models and save again
                    \app\models\TraineeTraining::deleteAll(['trainee_id'=>$id]);
                    foreach ($train->training_id as $t){
                        $tt = new \app\models\TraineeTraining();
                        $tt->trainee_id = $model->id;
                        $tt->training_id = $t;
                        $tt->save(false);
                    }
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }else {
            return $this->render('update', [
                'model' => $model,
                'training'=> $training,
                'train'=>$train,
                'upload' => $upload
            ]);
        }
    }
    */

    /**
     * Updates an existing Trainee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $training = [];
        $model = $this->findModel($id);
        $trainings = \app\models\TraineeTraining::find()->where(['trainee_id'=>$id])->indexBy('id')->all();
        foreach($trainings as $t){
            $training[$t->training_id] = ['SELECTED'=>'SELECTED'];
        }
        $train = new \app\models\TraineeTraining;

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $train->load(Yii::$app->request->post()) && $train->validate()) {
            $model->photo = $upload->dbName;
            $model->save();

            //delete traineetraining models and save again
            \app\models\TraineeTraining::deleteAll(['trainee_id'=>$id]);
            foreach ($train->training_id as $t){
                $tt = new \app\models\TraineeTraining();
                $tt->trainee_id = $model->id;
                $tt->training_id = $t;
                $tt->save(false);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }
        else {
            return $this->render('update', [
                'model' => $model,
                'training'=> $training,
                'train'=>$train,
            ]);
        }
    }

    /**
     * Deletes an existing Trainee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Trainee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Trainee the loaded model

views/trainee/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveForm;
use app\libraries\Options;
use app\models\State;
use app\models\Lga;
use app\models\Training;
use app\models\Healthfacility;
use yii\helpers\Url;
use yii\web\View;
use app\models\Ward;
/* @var $this yii\web\View */
/* @var $model app\models\Trainee */
/* @var $form yii\widgets\ActiveForm */
?>

<?php if (!$model->isNewRecord && $model->photo): ?>
<div class="row">
    <div class="col-sm-3 pull-right"><?= Html::img('photo-uploads/'.$model->photo) ?></div><br/>
</div>
<?php endif; ?>

<?php
$this->registerJs(
    "$('#multi-select').dropdown();",
    View::POS_END
);
?>

<div class="trainee-form">
    
    
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'class'=>'ui form'],
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-6\">{input}</div>\n\n<div class=\"col-lg-2\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
        ]); ?>
    
    <?= $form->errorSummary([$model]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'firstname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'middlename')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true,'class'=>'form-control phone']) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'dateofbirth')->widget(\yii\jui\DatePicker::className(), [
    // if you are using bootstrap, the following line will set the correct style of the input field
        'dateFormat'=>'yyyy-MM-dd',
        'options' => ['class' => 'form-control','dateFormat'=>'yy-mm-dd'],
                                                    'clientOptions' => ['dateFormat' => 'yy-mm-dd','changeMonth'=>'true', 'changeYear'=>'true', 'yearRange'=>'1900:2018']
    // ... you can configure more DatePicker properties here
        ]) 
    ?>

    <?= $form->field($model, 'gender')->dropDownList(Options::getGenderOptions(), ['prompt'=>'', 'class'=>'ui fluid dropdown']) ?>

    <?= $form->field($model, 'state_id')->dropDownList(State::getStateOptions(), ['prompt'=>'', 'class'=>'trainee-state ui search dropdown']) ?>

    <?= $form->field($model, 'lga_id')->dropDownList(Lga::getLgaOptions(),['prompt'=>'', 'class'=>'trainee-lga form-control']) ?>
    
    <?= $form->field($model, 'ward_id')->dropDownList(Ward::getWardOptions(),['prompt'=>'', 'class'=>'trainee-ward form-control']) ?>

    <?= $form->field($model, 'facility_id')->dropDownList(Healthfacility::getFacilityOptions(), ['prompt'=>'', 'class'=>'trainee-facility form-control']) ?>
    
    <?php if($model->isNewRecord): ?>
        <?= $form->field($training, 'training_id[]')->dropDownList(Training::getTrainingOptions(),
                ['multiple'=>'', 'class'=>'ui multiple selection dropdown', 'id'=>"multi-select"]) ?>
    <?php else: ?>
    <div class="form-group field-trainer-position required">
        <label class="col-lg-2 control-label" for="trainer-position">Position</label>
        <div class="col-lg-6">
        <?= 
            Html::activeDropDownList($train,'training_id[]', Training::getTrainingOptions(),
                    ['class'=>'form-control', 'multiple'=>'multiple', 'label'=>'Trainings', 'prompt'=>'Please Select', 'options'=>$training])?> 
        </div>
    </div>
    <?php endif; ?>

    <?= $form->field($model, 'serviceyears')->textInput() ?>

    <?= $form->field($model, 'position')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'latitude')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'longitude')->textInput(['maxlength' => true]) ?>
    
    <?php /* $form->field($model, 'comment')->textarea()*/ ?>

    <?php /* $form->field($upload, 'photo')->fileInput() */ ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<script>
var cleave = new Cleave('.phone', {
    blocks: [4, 3, 4],
    uppercase: true
});

//ajax calls
$(document).ready(function(){

    //get lgas on state change
    $('.trainee-state').change(function(){
        var state = $(this).val()
        $.post('/hworker/lga/get-state-lga-options',{'state':state}, function(data){
            $('.trainee-lga').empty().append(data)
        })
    })

    //get wards on lga change
    $('.trainee-lga').change(function(){
        var lga = $(this).val();
        $.post('/hworker/ward/get-lga-options',{'lga':lga}, function(data){
            $('.trainee-ward').empty().append(data);
        })
    })
})
</script>
<?php
/*
$this->registerJsFile(
    Url::base().'/web/js/lga_select.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
*/

views/trainee/_lga_report_table.php
<?php

use yii\helpers\Html;
use app\models\Healthfacility;
use app\models\TraineeTraining;
use yii\helpers\Url;
use yii\web\View;
?>

<?php if(empty($trainees)): ?>
<div class="alert alert-info">There are no trainees for the selected state</div>
<?php else: ?>
<!---------------------------------- show a card view of trainees --------------------------------------------->
<div class="row">
    <div class="col-md-6">
        <div class="ui statistic">
            <div class="value">
              <?= $ward_count ?>
            </div>
            <div class="label">
              Wards
            </div>
        </div>
        <div class="ui statistic">
            <div class="value">
              <?= count($trainees)?>
            </div>
            <div class="label">
              Health Workers
            </div>
        </div>
        <hr/>
        <p id="homechart"></p>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Map Distribution</div>
            <div class="panel-body">
                <h1>MAP NOT AVAILABLE</h1>
            </div>
        </div>
    </div>
</div>
<hr/>

<div class="row">
    <?php foreach($trainees as $t): ?>
    <div class="col-md-3">
        <div class="ui card">
            <div class="image">
                <?php if(isset($t->photo)): ?>
                    <?= Html::img(Url::base().'/photo-uploads/'.$t->photo) ?>
                <?php else: ?>
                    <?= Html::img(Url::base().'/web/img/person1.jpg') ?>
                <?php endif; ?>
              
            </div>
            <div class="content">
              <a class="header"><?= ucwords(strtolower($t->surname. " ".$t->firstname))?></a>
              <div class="meta">
                <span class="date"><?= ucwords($t->position) ?></span>
              </div>
              <div class="description">
                <?= Healthfacility::getName($t->facility_id)?>
              </div>
            </div>
            <div class="extra content">
              <span class="right floated">
                <?= Html::a('View Profile',['/trainee/view', 'id' => $t->id]) ?>
              </span>
              <span>
                <i class="user icon"></i>
                <?= TraineeTraining::getTrainingCount($t->id) ?> Training(s)
              </span>
            </div>
        </div>
        <br/>
    </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>

<script>
    var lga = "<?= app\models\Lga::getLgaName($lga_id) ?>";
    var distribution = JSON.parse('<?= $ward_distribution;?>');
    console.log(distribution)
</script>

<?php

$this->registerJsFile(
    Url::base().'/web/js/highcharts.js',
    ['position' => View::POS_HEAD]
);

$this->registerJs(
    "$(document).ready(function () {
        
    // Build the chart
    Highcharts.chart('homechart', {
    chart: {
        type: 'column'
    },
    title: {
        text: lga +' Local Government Area :Trainees per Ward'
    },
    subtitle: {
        text: 'Source: National Primary Health Care Development Agency'
    },
    xAxis: {
        type: 'category',
        labels: {
            //rotation: -45,
            style: {
                fontSize: '13px',
                fontFamily: 'Segoe ui light'
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Workers'
        }
    },
    legend: {
        enabled: false
    },
    tooltip: {
        pointFormat: 'Number of trainees: {point.y}</b>'
    },
    series: [{
        name: 'Population',
        data: distribution,
        
    }]
})
    
    
    
});",
    View::POS_READY,
    'my-button-handler'
);

views/trainee/_state_report_table.php
<?php

use yii\helpers\Html;
use app\models\Healthfacility;
use app\models\TraineeTraining;
use yii\helpers\Url;
use yii\web\View;
?>

<?php if(empty($trainees)): ?>
<div class="alert alert-info">There are no trainees for the selected state</div>
<?php else: ?>
<!---------------------------------- show a card view of trainees --------------------------------------------->
<div class="row">
    <div class="col-md-6">
        <div class="ui statistic">
            <div class="value">
              <?= $lga_count ?>
            </div>
            <div class="label">
              LGAs
            </div>
        </div>
        <div class="ui statistic">
            <div class="value">
              <?= $ward_count ?>
            </div>
            <div class="label">
              Wards
            </div>
        </div>
        <div class="ui statistic">
            <div class="value">
              <?= count($trainees)?>
            </div>
            <div class="label">
              Health Workers
            </div>
        </div>
        <hr/>
        <p id="homechart"></p>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Map Distribution</div>
            <div class="panel-body">
                <?php if($state_id != 37): ?>
                    <h1>MAP NOT AVAILABLE</h1>
                <?php else: ?>
                    <p id="mapid"></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<hr/>

<div class="row">
    <?php foreach($trainees as $t): ?>
    <div class="col-md-3" id="state-trainee-report">
        <div class="ui card">
            <div class="image">
                <?php if(isset($t->photo)): ?>
                    <?= Html::img(Url::base().'/photo-uploads/'.$t->photo) ?>
                <?php else: ?>
                    <?= Html::img(Url::base().'/web/img/person1.jpg',['class'=>'trainee-placeholder-img']) ?>
                <?php endif; ?>              
            </div>
            <div class="content">
              <a class="header"><?= ucwords(strtolower($t->surname. " ".$t->firstname))?></a>
              <div class="meta">
                <span class="date"><?= ucwords($t->position) ?></span>
              </div>
              <div class="description">
                <?= Healthfacility::getName($t->facility_id)?>
              </div>
            </div>
            <div class="extra content">
              <span class="right floated">
                <?= Html::a('View Profile',['/trainee/view', 'id' => $t->id]) ?>
              </span>
              <span>
                <i class="user icon"></i>
                <?= TraineeTraining::getTrainingCount($t->id) ?> Training(s)
              </span>
            </div>
        </div>
        <br/>
    </div>
    <?php endforeach; ?>
    </div>

	
<?php endif; ?>
<script>
    var state = "<?= app\models\State::getStateName($state_id) ?>";
    var distribution = JSON.parse('<?= $lga_distribution;?>');
</script>


<?php
$this->registerJsFile(
    Url::base().'/web/js/highcharts.js',
    ['position' => View::POS_HEAD]
);

$this->registerJs(
    "$(document).ready(function () {
    
    // Build the chart
    Highcharts.chart('homechart', {
    chart: {
        type: 'column'
    },
    title: {
        text: state +' State :Trainees per Local Government'
    },
    subtitle: {
        text: 'Source: National Primary Health Care Development Agency'
    },
    xAxis: {
        type: 'category',
        labels: {
            //rotation: -45,
            style: {
                fontSize: '13px',
                fontFamily: 'Segoe ui light'
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Workers'
        }
    },
    legend: {
        enabled: false
    },
    tooltip: {
        pointFormat: 'Number of trainees: {point.y}</b>'
    },
    series: [{
        name: 'Population',
        data: distribution,
        
    }]
})
    
    
    
});",
    View::POS_READY,
    'my-button-handler'
);